// Generated by gencpp from file geometry_constraints/geom_constrRequest.msg
// DO NOT EDIT!


#ifndef GEOMETRY_CONSTRAINTS_MESSAGE_GEOM_CONSTRREQUEST_H
#define GEOMETRY_CONSTRAINTS_MESSAGE_GEOM_CONSTRREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace geometry_constraints
{
template <class ContainerAllocator>
struct geom_constrRequest_
{
  typedef geom_constrRequest_<ContainerAllocator> Type;

  geom_constrRequest_()
    : x()
    , y()
    , z()  {
      x.assign(0.0);

      y.assign(0.0);

      z.assign(0.0);
  }
  geom_constrRequest_(const ContainerAllocator& _alloc)
    : x()
    , y()
    , z()  {
  (void)_alloc;
      x.assign(0.0);

      y.assign(0.0);

      z.assign(0.0);
  }



   typedef boost::array<double, 6>  _x_type;
  _x_type x;

   typedef boost::array<double, 6>  _y_type;
  _y_type y;

   typedef boost::array<double, 6>  _z_type;
  _z_type z;





  typedef boost::shared_ptr< ::geometry_constraints::geom_constrRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::geometry_constraints::geom_constrRequest_<ContainerAllocator> const> ConstPtr;

}; // struct geom_constrRequest_

typedef ::geometry_constraints::geom_constrRequest_<std::allocator<void> > geom_constrRequest;

typedef boost::shared_ptr< ::geometry_constraints::geom_constrRequest > geom_constrRequestPtr;
typedef boost::shared_ptr< ::geometry_constraints::geom_constrRequest const> geom_constrRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::geometry_constraints::geom_constrRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::geometry_constraints::geom_constrRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace geometry_constraints

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::geometry_constraints::geom_constrRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::geometry_constraints::geom_constrRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::geometry_constraints::geom_constrRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::geometry_constraints::geom_constrRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::geometry_constraints::geom_constrRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::geometry_constraints::geom_constrRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::geometry_constraints::geom_constrRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "334c68cc5a82d88dbceb248107ad91df";
  }

  static const char* value(const ::geometry_constraints::geom_constrRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x334c68cc5a82d88dULL;
  static const uint64_t static_value2 = 0xbceb248107ad91dfULL;
};

template<class ContainerAllocator>
struct DataType< ::geometry_constraints::geom_constrRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_constraints/geom_constrRequest";
  }

  static const char* value(const ::geometry_constraints::geom_constrRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::geometry_constraints::geom_constrRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[6] x\n\
float64[6] y\n\
float64[6] z\n\
";
  }

  static const char* value(const ::geometry_constraints::geom_constrRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::geometry_constraints::geom_constrRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct geom_constrRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::geometry_constraints::geom_constrRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::geometry_constraints::geom_constrRequest_<ContainerAllocator>& v)
  {
    s << indent << "x[]" << std::endl;
    for (size_t i = 0; i < v.x.size(); ++i)
    {
      s << indent << "  x[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.x[i]);
    }
    s << indent << "y[]" << std::endl;
    for (size_t i = 0; i < v.y.size(); ++i)
    {
      s << indent << "  y[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.y[i]);
    }
    s << indent << "z[]" << std::endl;
    for (size_t i = 0; i < v.z.size(); ++i)
    {
      s << indent << "  z[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.z[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // GEOMETRY_CONSTRAINTS_MESSAGE_GEOM_CONSTRREQUEST_H
