// Generated by gencpp from file geometry_constraints/geom_constr.msg
// DO NOT EDIT!


#ifndef GEOMETRY_CONSTRAINTS_MESSAGE_GEOM_CONSTR_H
#define GEOMETRY_CONSTRAINTS_MESSAGE_GEOM_CONSTR_H

#include <ros/service_traits.h>


#include <geometry_constraints/geom_constrRequest.h>
#include <geometry_constraints/geom_constrResponse.h>


namespace geometry_constraints
{

struct geom_constr
{

typedef geom_constrRequest Request;
typedef geom_constrResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct geom_constr
} // namespace geometry_constraints


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::geometry_constraints::geom_constr > {
  static const char* value()
  {
    return "0ed687e416f05d17d89e19dfe16dcb99";
  }

  static const char* value(const ::geometry_constraints::geom_constr&) { return value(); }
};

template<>
struct DataType< ::geometry_constraints::geom_constr > {
  static const char* value()
  {
    return "geometry_constraints/geom_constr";
  }

  static const char* value(const ::geometry_constraints::geom_constr&) { return value(); }
};


// service_traits::MD5Sum< ::geometry_constraints::geom_constrRequest> should match 
// service_traits::MD5Sum< ::geometry_constraints::geom_constr > 
template<>
struct MD5Sum< ::geometry_constraints::geom_constrRequest>
{
  static const char* value()
  {
    return MD5Sum< ::geometry_constraints::geom_constr >::value();
  }
  static const char* value(const ::geometry_constraints::geom_constrRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::geometry_constraints::geom_constrRequest> should match 
// service_traits::DataType< ::geometry_constraints::geom_constr > 
template<>
struct DataType< ::geometry_constraints::geom_constrRequest>
{
  static const char* value()
  {
    return DataType< ::geometry_constraints::geom_constr >::value();
  }
  static const char* value(const ::geometry_constraints::geom_constrRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::geometry_constraints::geom_constrResponse> should match 
// service_traits::MD5Sum< ::geometry_constraints::geom_constr > 
template<>
struct MD5Sum< ::geometry_constraints::geom_constrResponse>
{
  static const char* value()
  {
    return MD5Sum< ::geometry_constraints::geom_constr >::value();
  }
  static const char* value(const ::geometry_constraints::geom_constrResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::geometry_constraints::geom_constrResponse> should match 
// service_traits::DataType< ::geometry_constraints::geom_constr > 
template<>
struct DataType< ::geometry_constraints::geom_constrResponse>
{
  static const char* value()
  {
    return DataType< ::geometry_constraints::geom_constr >::value();
  }
  static const char* value(const ::geometry_constraints::geom_constrResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GEOMETRY_CONSTRAINTS_MESSAGE_GEOM_CONSTR_H
