<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="hexapod_leg">

  <xacro:property name="body_width_s" value="0.125"/>
  <xacro:property name="body_width_b" value="0.145"/>
  <xacro:property name="body_length" value="0.205"/>
  <xacro:property name="body_heigth" value="0.04"/>
  <xacro:property name="L1_length" value="0.034"/>
  <xacro:property name="L2_length" value="0.087"/>
  <xacro:property name="L3_length" value="0.1273"/>
  <xacro:property name="L1_length" value="0.034"/>
  <xacro:property name="L_width" value="0.02"/>

  <xacro:property name="body_mass" value="0.3"/>
  <xacro:property name="L1_mass" value="0.158"/>
  <xacro:property name="L2_mass" value="0.034"/>
  <xacro:property name="L3_mass" value="0.102"/>

  <xacro:property name="max_angle" value="150"/>


  <xacro:macro name="default_inertial" params="mass">
    <inertial>
      <mass value="${mass}" />
      <inertia ixx="1.0" ixy="0.0" ixz="0.0"
        iyy="1.0" iyz="0.0"
        izz="1.0" />
      </inertial>
    </xacro:macro>

    <link name="base_link" />

    <joint name="base_joint" type="fixed">
      <parent link="base_link" />
      <child link="body" />
      <origin xyz="0 0 0" rpy="0 0 0" />
    </joint>

    <link name="body">
      <visual>
        <geometry>
          <box size="${body_length} ${body_width_s} ${body_heigth}"/>
        </geometry>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <material name="white">
          <color rgba="1 1 1 1"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <box size="${body_length} ${body_width_s} ${body_heigth}"/>
        </geometry>
      </collision>
      <xacro:default_inertial mass="${body_mass}"/>
    </link>

    <link name="leg_center_1" />

    <joint name="leg_center_joint" type="fixed">
      <parent link="body"/>
      <child link="leg_center_1"/>
      <origin rpy="0 0 -1.57" xyz="0 ${-body_width_b/2} 0"/>
    </joint>

    <link name="leg_L1">
      <visual>
        <geometry>
          <box size="${L1_length} ${L_width} ${L_width}"/>
        </geometry>
        <origin rpy="0 0 0" xyz="${L1_length/2} 0 0"/>
        <material name="yellow">
          <color rgba="255 255 0 1"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <box size="${L1_length} ${L_width} ${L_width}"/>
        </geometry>
      </collision>
      <xacro:default_inertial mass="${L1_mass}"/>
    </link>

    <joint name="coxa_joint" type="revolute">
      <parent link="leg_center_1"/>
      <child link="leg_L1"/>
      <axis xyz="0 0 1"/>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <limit effort ="1000.0" lower="${radians(-max_angle)}" upper="${radians(max_angle)}" velocity="0.5"/>
    </joint>
    

    <link name="leg_L2">
      <visual>
        <geometry>
          <box size="${L2_length} ${L_width} ${L_width}"/>
        </geometry>
        <origin rpy="0 0 0" xyz="${L2_length/2} 0 0"/>
        <material name="green">
          <color rgba="255 0 255 1"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <box size="${L2_length} ${L_width} ${L_width}"/>
        </geometry>
      </collision>
      <xacro:default_inertial mass="${L2_mass}"/>
    </link>

    <joint name="femur_joint" type="revolute">
      <parent link="leg_L1"/>
      <child link="leg_L2"/>
      <origin rpy="1.57 0 0" xyz="${L1_length} 0 0"/>
      <axis xyz="0 0 1"/>
      <limit effort ="1000.0" lower="${radians(-max_angle)}" upper="${radians(max_angle)}" velocity="0.5"/>
    </joint>


    <link name="leg_L3">
      <visual>
        <geometry>
          <box size="${L3_length} ${L_width} ${L_width}"/>
        </geometry>
        <origin rpy="0 0 0" xyz="${L3_length/2} 0 0"/>
        <material name="blue">
          <color rgba="0 255 255 1"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <box size="${L3_length} ${L_width} ${L_width}"/>
        </geometry>
      </collision>
      <xacro:default_inertial mass="${L3_mass}"/>
    </link>

    <joint name="tibia_joint" type="revolute">
      <parent link="leg_L2"/>
      <child link="leg_L3"/>
      <origin rpy="0 0 0" xyz="${L2_length} 0 0"/>
      <axis xyz="0 0 -1"/>
      <limit effort ="1000.0" lower="${radians(-max_angle)}" upper="${radians(max_angle)}" velocity="0.5"/>
    </joint>

    <link name="end_effector"/>

     <joint name="end effector_joint" type="fixed">
      <parent link="leg_L3"/>
      <child link="end_effector"/>
      <origin rpy="0 0 0" xyz="${L3_length} 0 0"/>
    </joint>


  </robot>
