// Generated by gencpp from file leg_msgs/LegJointState.msg
// DO NOT EDIT!


#ifndef LEG_MSGS_MESSAGE_LEGJOINTSTATE_H
#define LEG_MSGS_MESSAGE_LEGJOINTSTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace leg_msgs
{
template <class ContainerAllocator>
struct LegJointState_
{
  typedef LegJointState_<ContainerAllocator> Type;

  LegJointState_()
    : joint()  {
      joint.assign(0.0);
  }
  LegJointState_(const ContainerAllocator& _alloc)
    : joint()  {
  (void)_alloc;
      joint.assign(0.0);
  }



   typedef boost::array<double, 3>  _joint_type;
  _joint_type joint;





  typedef boost::shared_ptr< ::leg_msgs::LegJointState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::leg_msgs::LegJointState_<ContainerAllocator> const> ConstPtr;

}; // struct LegJointState_

typedef ::leg_msgs::LegJointState_<std::allocator<void> > LegJointState;

typedef boost::shared_ptr< ::leg_msgs::LegJointState > LegJointStatePtr;
typedef boost::shared_ptr< ::leg_msgs::LegJointState const> LegJointStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::leg_msgs::LegJointState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::leg_msgs::LegJointState_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace leg_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'leg_msgs': ['/home/yoggi/hexapod_ws/src/leg_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::leg_msgs::LegJointState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::leg_msgs::LegJointState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::leg_msgs::LegJointState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::leg_msgs::LegJointState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::leg_msgs::LegJointState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::leg_msgs::LegJointState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::leg_msgs::LegJointState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8c9183fb9f551c0c8a1fa0044edf51fc";
  }

  static const char* value(const ::leg_msgs::LegJointState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8c9183fb9f551c0cULL;
  static const uint64_t static_value2 = 0x8a1fa0044edf51fcULL;
};

template<class ContainerAllocator>
struct DataType< ::leg_msgs::LegJointState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "leg_msgs/LegJointState";
  }

  static const char* value(const ::leg_msgs::LegJointState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::leg_msgs::LegJointState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[3] joint\n\
";
  }

  static const char* value(const ::leg_msgs::LegJointState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::leg_msgs::LegJointState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.joint);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LegJointState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::leg_msgs::LegJointState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::leg_msgs::LegJointState_<ContainerAllocator>& v)
  {
    s << indent << "joint[]" << std::endl;
    for (size_t i = 0; i < v.joint.size(); ++i)
    {
      s << indent << "  joint[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.joint[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // LEG_MSGS_MESSAGE_LEGJOINTSTATE_H
